### PR TITLE
Cashu v1 Endpoints for Melt and mint quotes

### PR DESCRIPTION
**Pull request by richarddushime**
Work in progress

### CODE REVIEW

**Comment by Kodylow** [comment]
Is this still being worked on? I made some updates to make this easier using notesJson, encode, and decode

**Comment by richarddushime** [comment]
> Is this still being worked on? I made some updates to make this easier using notesJson, encode, and decode

yes sir , and i m sorry it has taken long.

**Comment by Kodylow** [comment]
okay can you rebase and keep this updated then for progress, otherwise I'm going to take it back over, this is blocking a couple other projectts

**Comment by Kodylow** [comment]
closing

**Pull request closed without merging**
